language: java
script: mvn test -Pnolog,$TEST_EXECUTION_PROFILE
jdk:
  - oraclejdk8
env:
  - TEST_EXECUTION_PROFILE=test
  - TEST_EXECUTION_PROFILE=accumulo-test
  - TEST_EXECUTION_PROFILE=elasticsearch-test
  - TEST_EXECUTION_PROFILE=multimodule-test
branches:
  only:
    - master
    - 2.5.x
addons:
  apt:
    packages:
      - oracle-java8-installer