language: java
script: mvn test -P$TEST_EXECUTION_PROFILE
jdk:
  - oraclejdk8
env:
  - TEST_EXECUTION_PROFILE=test
  - TEST_EXECUTION_PROFILE=accumulo-test
  - TEST_EXECUTION_PROFILE=blueprints-test
  - TEST_EXECUTION_PROFILE=cypher-test
  - TEST_EXECUTION_PROFILE=nolog,elasticsearch-test
  - TEST_EXECUTION_PROFILE=multimodule-test
branches:
  only:
    - master
    - 2.5.x
    - refactor-blueprints-testing
cache:
  directories:
    - $HOME/.m2/repository
addons:
  apt:
    packages:
      - oracle-java8-installer
